# Generated by Django 3.0.5 on 2020-10-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201003_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='meating',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
