# Generated by Django 3.0.5 on 2020-10-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201004_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='voted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
