# Generated by Django 3.0.5 on 2020-10-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201004_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='var1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='code',
        ),
        migrations.RemoveField(
            model_name='task',
            name='var2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='var3',
        ),
        migrations.AddField(
            model_name='game',
            name='auth',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='code1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='code2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='codefinal',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='location1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='location2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='location3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
