# Generated by Django 3.0.5 on 2020-12-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201006_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
